name: Continuous Deployment (CD)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
      - name: Set up Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install package dependencies
        run: npm ci
      - name: Build the app
        run: npm run build
      - name: Deploy the app
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build
